### ISSUE TITLE
Re:VIEW ファイルの変更を自動検知してPDF ファイルを出力する仕組みの作成

### ISSUE THREAD

**Issue by TsutomuNakamura** [a6s-cloud/grouscope-books#6]
Re:VIEW ファイルの追加/変更/削除を自動検知して更新するスクリプトを作成する。
// 手元で自動ビルド的な仕組みできそうだったので後ほどプルリクします。ビルドのコマンドを覚えられない人向けです

**Comment by nsuzuki7713** [comment]
おぉー、これは嬉しいです！！
ワシ向けやぁぁぁぁー👴

**Comment by TsutomuNakamura** [comment]
笑！PDF 出力するコマンド覚えれれんのじゃー👴！
